# Generated by Django 5.1 on 2024-09-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapi', '0004_dwolla_customer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plaidaccount',
            name='updated_at',
        ),
    ]
