# Generated by Django 5.1.1 on 2024-09-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapi', '0006_alter_plaidaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='institution_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PlaidBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_subtype', models.CharField(max_length=50)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plaid_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaidapi.plaidaccount')),
            ],
        ),
    ]
