# Generated by Django 5.1.1 on 2024-09-16 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapi', '0009_fundingsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingsource',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='fundingsource',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='funding_source_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
