# Generated by Django 5.1.1 on 2024-09-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapi', '0010_remove_fundingsource_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PlaidBankAccount',
        ),
    ]
