# Generated by Django 5.1 on 2024-09-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plaidapi', '0013_fundingsource_plaid_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='transectionCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.CharField(max_length=500)),
                ('plaid_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_cursor', to='plaidapi.plaidaccount')),
            ],
        ),
    ]
