# Generated by Django 5.1 on 2024-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_signup_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Zip_Code',
            field=models.CharField(max_length=6),
        ),
    ]
