# Generated by Django 5.1 on 2024-08-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_signup_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='User_Name',
            field=models.CharField(default='user_100', max_length=70),
        ),
    ]
