# Generated by Django 5.1 on 2024-08-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_signup_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='User_Name',
            field=models.CharField(default='user', max_length=70),
        ),
    ]
