# Generated by Django 5.1 on 2024-08-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_name_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
