# Generated by Django 5.1 on 2024-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
