# Generated by Django 5.1 on 2024-08-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_signup_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
