# Generated by Django 5.1 on 2024-09-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userfinancialdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFinancialData',
        ),
    ]
