# Generated by Django 5.1 on 2024-09-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userfinancialdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFinancialData',
        ),
    ]
